export global ReaderState {
    in-out property <bool> reader-available: false;
    in-out property <bool> reading: false;
    in-out property <bool> has-spool: false;
    in-out property <string> status-text: "Starting RFID reader…";

    in-out property <string> material-name: "";
    in-out property <string> material-detail: "";
    in-out property <string> color-name: "";
    in-out property <string> color-code: "";
    in-out property <string> bambu-color-code: "";
    in-out property <color> primary-color: #333b45;
    in-out property <color> secondary-color: #333b45;
    in-out property <bool> has-secondary-color: false;

    in-out property <string> physical-parameters: "";
    in-out property <string> temperature-parameters: "";
    in-out property <string> drying-parameters: "";
    in-out property <string> production-parameters: "";
    in-out property <string> identifier-parameters: "";

    in-out property <bool> wifi-setup-active: false;
    in-out property <string> wifi-url: "";
    in-out property <string> wifi-ssid: "";
    in-out property <string> wifi-key: "";
}
